### ISSUE TITLE
Set up instructions for setup with running calcs in a single dataset

### ISSUE THREAD

**Issue by mrchrisadams** [thegreenwebfoundation/datasets#1]
Martin and I had some success making a little npm module for the greenhouse gases dataset, with the aim of being able to require it for use in other modules you might use for calculating emissions for delivery, or other uses.

https://github.com/mamhoff/ameeless-planet-greenhousegases-gwp

We agreed it would make sense to work on it as a for in the Green Web Foundation, and find a way to break this repo into a series of smaller npm modules that can be installed separately.

So when, in Bret Viktor writes in [What can a technologist do about climate change? A personal view](view-source:http://worrydream.com/ClimateChange/)

> What if there were an “npm” for scientific models?

And mentions some sample code like:

```javascript
var lighting = require(’residential-lighting-energy-model’);

var energyPerYear = lighting.getEnergyPerYear({
    zipCode: 94110,
    houseSize: "small",
    occupants: 3,
    fluorescentFraction: 0.75,
});

```

This would in theory, be possible. You could do something like:

```
npm install @tgwf/datasets-delivery-emissions-model
```

Then you'd be able to call it like the example above.

We're starting with the gases dataset, because different models emit data as different gases, and we want to be able to convert emissions to carbon dioxide equivalent.

### Todo 

- [ ] get tests set up for single dataset
- [x] add script to convert `item def` csv to actual csv 
- [ ] move in script to precompile the csv file to json, to remove the need for any csv deps installing
- [x] document assumed plan for converting other datasets
